analyzer:
  errors:
    avoid_types_as_parameter_names: ignore
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml
