name: food_court_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  gap: ^3.0.1

  # maps
  google_map_polyline_new: ^0.3.0+2
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^2.2.0
  location: ^6.0.2
  http: ^1.2.1
  
  # database
  firebase_messaging: ^15.1.2
  firebase_storage: ^12.1.0
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  
  currency_text_input_formatter: ^2.2.3
  flutter_local_notifications: ^17.2.3
  loading_animation_widget: ^1.2.1
  double_back_to_close_app: ^2.1.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  blue_thermal_printer: ^1.2.3
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  custom_info_window: ^1.0.1
  flutter_rating_bar: ^4.0.1
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.3
  flutter_slidable: ^3.1.1
  another_flushbar: ^1.12.30
  image_picker: ^1.1.2
  label_marker: ^1.0.1
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  fl_chart: ^0.68.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  pinput: ^5.0.0
  intl: ^0.19.0
  uuid: ^4.4.0
  firebase_analytics: ^11.3.2
  sensors_plus: ^6.0.1


  
flutter_native_splash:
  image: 'assets/images/splash-screen.png'
  color: '#2979FF'

  image_dark: 'assets/images/splash-screen.png'
  color_dark: '#212121'

  android_12: 
    image: 'assets/images/splash-screen.png'
    color: '#2979FF'

    image_dark: 'assets/images/splash-screen.png'
    color_dark: '#212121'


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  
flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/weathers/
    - assets/weathers/day/
    - assets/weathers/night/
    - assets/images/
    - assets/images/logo/
    - assets/images/test/
    - assets/images/menu/
    - assets/mapicons/
    - assets/fonts/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-SemiBold.otf
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
